<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_gecobekevingmail.com_lucide lucide-log-_e2e147</name>
   <tag></tag>
   <elementGuidId>738536a0-cafa-44d3-acee-359cb9ed5c98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='gecobekevin@gmail.com'])[2]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.lucide.lucide-log-out.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>72edc66a-b17e-48d7-9886-2ae56a3694fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>73581544-87ed-4996-864b-47e9264b0c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>d19cfa3e-120f-4191-8ac0-e83b88b86f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>2c40682d-41f7-4835-9a86-7648d61c0c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>cc198fe4-d10b-421d-a455-6a43642ae47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6457772d-a4a4-442f-a813-9f046ec4f111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#A3A3A3</value>
      <webElementGuid>15d5aaba-4b68-45f4-bffc-22c7653cd9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5497cb68-bd1e-41d5-9d40-c2c8264c3d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>d8f73478-28f0-440e-860e-546bee1ddfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>3a067c91-cb74-4ac6-9c45-f336456b60f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lucide lucide-log-out cursor-pointer</value>
      <webElementGuid>9cf3c44b-6d17-4cbf-a61f-6712a4ccdc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:r4:&quot;)/div[@class=&quot;absolute -right-5 w-[375px] overflow-auto rounded-sm border border-gray-800 bg-gray-950 shadow-lg&quot;]/div[@class=&quot;max-h-[calc(100vh-120px)]&quot;]/div[@class=&quot;px-2 py-1.5 text-sm font-semibold&quot;]/div[@class=&quot;flex justify-between p-xl pb-xl&quot;]/svg[@class=&quot;lucide lucide-log-out cursor-pointer&quot;]</value>
      <webElementGuid>74ad08bf-046d-489c-b6ed-e2e4a5ae98a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gecobekevin@gmail.com'])[2]/following::*[name()='svg'][1]</value>
      <webElementGuid>23537310-3845-47c1-8d7b-270a87201009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kevin Gecobe'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>571c7afc-7afe-4984-9e3e-8fbe861de760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome back, Kevin'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>039edc4a-9af2-402b-b1b9-fa223510bfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Here is your wallet summary:'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>feb81458-6a39-466d-b87a-3343127f8cd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
