<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Forgot password_a-vqujb73gg6lx</name>
   <tag></tag>
   <elementGuidId>ab836251-128e-4bd2-a813-148332b10f80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-vqujb73gg6lx']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-vqujb73gg6lx&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3591a468-d751-4cbc-84a5-2bca27ac7d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>b033ab9c-251e-4424-a9aa-9fff067fbd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>ed325adb-460f-4769-8632-4c59da75ebaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>8a7afe1f-e752-470a-844b-cc29e106160b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>0321dbf4-9e86-4d2e-a04c-08e7f79fad05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-vqujb73gg6lx</value>
      <webElementGuid>8af7da65-76a8-4c99-a578-2b81e8c427b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>829dfc3c-92db-48ba-9240-60e34a403a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f274cdf7-ebe5-4855-90be-4c763ea89b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>824b4f12-0f06-42dd-aef3-ca26389b92c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdUyJcpAAAAAMUJFqSUSnqrFqTvEobZ6ArAg792&amp;co=aHR0cHM6Ly9rZXljbG9hay5wZXJtaXNzaW9uLmlvOjQ0Mw..&amp;hl=en&amp;v=pPK749sccDmVW_9DSeTMVvh2&amp;theme=dark&amp;size=normal&amp;cb=irbtg6winefi</value>
      <webElementGuid>de171e5e-513f-4639-9027-dd64b568795b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-form-login&quot;)/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>1961e065-e758-4fd4-bbda-a01e364a84f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-vqujb73gg6lx']</value>
      <webElementGuid>7bf40a9b-2a5b-4073-9718-5a9c22d94e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-form-login']/div[4]/div/div/iframe</value>
      <webElementGuid>d13d2ade-0a2b-454c-a0f2-08b31970f0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4c59867d-bcda-4aa1-b6c6-2c7fa894a358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-vqujb73gg6lx' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdUyJcpAAAAAMUJFqSUSnqrFqTvEobZ6ArAg792&amp;co=aHR0cHM6Ly9rZXljbG9hay5wZXJtaXNzaW9uLmlvOjQ0Mw..&amp;hl=en&amp;v=pPK749sccDmVW_9DSeTMVvh2&amp;theme=dark&amp;size=normal&amp;cb=irbtg6winefi']</value>
      <webElementGuid>878ef85e-2d8d-40b4-82d0-d766d87b0fd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
