<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Forgot password_a-28dim5pj4qe9</name>
   <tag></tag>
   <elementGuidId>8e6e6ab7-ae30-49d7-bd6b-7b1c4aa283d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-28dim5pj4qe9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-28dim5pj4qe9&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a7cb085c-1b26-47c6-bce2-18484fdadfc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>bd6477bd-dc27-4f7c-888a-50fdcc83297e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>205fdd53-08b9-4402-9e1c-f80de04cc626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>07d54972-4c77-4a18-a402-3631876f85eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ee96585e-1944-4d3f-8bd0-b9c499ce2a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-28dim5pj4qe9</value>
      <webElementGuid>2b7cb3fb-1b4d-46fb-b247-822cd133e5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>05447ab6-7ce3-4792-a818-acc56b1fc8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f79d9182-db0d-4df4-a5e8-e5dc01375f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>c92f1a27-a0d0-4767-91bb-47044d55d7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdUyJcpAAAAAMUJFqSUSnqrFqTvEobZ6ArAg792&amp;co=aHR0cHM6Ly9rZXljbG9hay5wZXJtaXNzaW9uLmlvOjQ0Mw..&amp;hl=en&amp;v=pPK749sccDmVW_9DSeTMVvh2&amp;theme=dark&amp;size=normal&amp;cb=t68maft8181n</value>
      <webElementGuid>383f9d02-3c67-4a42-894f-fc3006425175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-form-login&quot;)/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>5de65cc6-5e44-4a3c-ae79-c1d1b3314cdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-28dim5pj4qe9']</value>
      <webElementGuid>b5fe29b3-7ca8-44da-a6e0-fc9809c9fcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-form-login']/div[4]/div/div/iframe</value>
      <webElementGuid>332cbd90-452d-4573-b53e-bfe812c24aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1724ee64-726d-4fcb-8f81-bdac60ee726d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-28dim5pj4qe9' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdUyJcpAAAAAMUJFqSUSnqrFqTvEobZ6ArAg792&amp;co=aHR0cHM6Ly9rZXljbG9hay5wZXJtaXNzaW9uLmlvOjQ0Mw..&amp;hl=en&amp;v=pPK749sccDmVW_9DSeTMVvh2&amp;theme=dark&amp;size=normal&amp;cb=t68maft8181n']</value>
      <webElementGuid>7a8ee42d-6b14-4885-9c13-9345f0552e29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
