<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Forgot password_a-thvijx5wqjs7</name>
   <tag></tag>
   <elementGuidId>219e774e-0efc-47c1-92fb-a5b66cf0eb26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-thvijx5wqjs7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-thvijx5wqjs7&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8cf0990f-cd08-4f74-977e-ea26edbdfe05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>4360edca-e014-42d0-8cd3-d32346942fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>62a40cb7-1cff-4564-a620-1c3b80f4b841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>ba26219d-db29-466d-99e8-5302fb946816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>69aab149-4dc8-4042-b3af-2428f186402e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-thvijx5wqjs7</value>
      <webElementGuid>1d3d2553-ba56-44a5-9c63-28145e53a66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d7b59f30-4fb5-434d-94c8-3230b3e38a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>58ca01bc-46e9-412d-8d66-1521b77e9c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>cef6eb2c-71e5-4026-ab8e-91118854fe36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdUyJcpAAAAAMUJFqSUSnqrFqTvEobZ6ArAg792&amp;co=aHR0cHM6Ly9rZXljbG9hay5wZXJtaXNzaW9uLmlvOjQ0Mw..&amp;hl=en&amp;v=pPK749sccDmVW_9DSeTMVvh2&amp;theme=dark&amp;size=normal&amp;cb=xw10vbuox4b4</value>
      <webElementGuid>149e1e28-97db-4328-9106-d049ca91f090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-form-login&quot;)/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>823aff29-485f-47e9-9955-d3d52082c480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-thvijx5wqjs7']</value>
      <webElementGuid>10d8de10-3c73-44d9-b2ad-553f49260f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kc-form-login']/div[4]/div/div/iframe</value>
      <webElementGuid>bc97adbd-5026-439b-9617-00de4e344329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>123b908b-7c2d-40a3-a106-f7f049273baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-thvijx5wqjs7' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdUyJcpAAAAAMUJFqSUSnqrFqTvEobZ6ArAg792&amp;co=aHR0cHM6Ly9rZXljbG9hay5wZXJtaXNzaW9uLmlvOjQ0Mw..&amp;hl=en&amp;v=pPK749sccDmVW_9DSeTMVvh2&amp;theme=dark&amp;size=normal&amp;cb=xw10vbuox4b4']</value>
      <webElementGuid>214f1fdc-1f78-4d50-8264-ce495cb25138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
