<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Log in</name>
   <tag></tag>
   <elementGuidId>a3ffb5e7-3499-4f8f-a166-e84fc6c4ff7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63648609-e5ff-4ed9-8b8c-3ee788c790fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c7c47987-df0c-4fee-9903-1febb12e4627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-around whitespace-nowrap rounded-md disabled:pointer-events-none w-fit text-gray-300 bg-gray-900 hover:bg-gray-800 border border-gray-800 hover:border-gray-700 disabled:border-gray-200 disabled:bg-gray-100 disabled:text-gray-400 ring-gray-shadow-xs h-11 py-2.5 px-xl text-md-semibold gap-sm w-full !border-gray-300 !bg-transparent !text-brand-600 hover:!bg-brand-600 hover:!text-white</value>
      <webElementGuid>4525a886-061f-46de-98a1-b61986b6400b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>663d318d-206e-41ca-8355-248fe25ec3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-screen flex-col&quot;]/div[@class=&quot;h-auto&quot;]/header[@class=&quot;sticky top-0 z-50 w-full bg-white&quot;]/div[@class=&quot;relative z-50 flex justify-between px-xl py-2xl md:px-4xl mx-auto max-w-[1460px] items-center lg:max-w-[1195px]&quot;]/div[@class=&quot;flex items-center gap-2xl pl-4xl&quot;]/button[@class=&quot;inline-flex items-center justify-around whitespace-nowrap rounded-md disabled:pointer-events-none w-fit text-gray-300 bg-gray-900 hover:bg-gray-800 border border-gray-800 hover:border-gray-700 disabled:border-gray-200 disabled:bg-gray-100 disabled:text-gray-400 ring-gray-shadow-xs h-11 py-2.5 px-xl text-md-semibold gap-sm w-full !border-gray-300 !bg-transparent !text-brand-600 hover:!bg-brand-600 hover:!text-white&quot;]</value>
      <webElementGuid>f84adb8e-870c-4608-a59e-7a44e1bb668f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>1cf26d24-5686-41a0-9ca3-90e6678048be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/header/div[2]/div[2]/button</value>
      <webElementGuid>f02c9d3f-0e11-40f9-91ab-443fcf640506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permission For Brands'])[1]/following::button[1]</value>
      <webElementGuid>7e523f37-53c5-45ed-b11f-a2e984c405af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign-up today to earn 1,000 ASK*'])[1]/following::button[2]</value>
      <webElementGuid>9179606d-5462-4c4b-97a4-944488523138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/preceding::button[1]</value>
      <webElementGuid>e655f0d1-983b-4a33-b8a2-5d8bf099d906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log in']/parent::*</value>
      <webElementGuid>0a406290-6794-4aac-a2ae-032be280c8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>aea05347-30fe-4b70-afc0-d6ab196165a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Log in' or . = 'Log in')]</value>
      <webElementGuid>4d2febf1-ff7f-42dd-9579-d6bbd52c458b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
